name: 🚀 Deploy NestJS Blog Backend API to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy project to VPS
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        source: "."
        target: "/root/paredes_erick/pagina_backend"

    - name: Run deploy commands on VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        script: |
          cd /root/paredes_erick/pagina_backend
           # Matar el proceso que está usando el puerto 3014
          echo "Matar proceso en el puerto 3014..."
          sudo lsof -t -i:3014 | xargs sudo kill -9
          
          echo -e "$${{ secrets.ENV_FILE }}" > .env
          npm install
          npm run build
          # Reiniciar PM2 con el nuevo código
          pm2 stop estadisticas-api || true
          pm2 delete estadisticas-api || true
          pm2 start dist/main.js --name estadisticas-api